export enum LoadState {
    STARTUP,
    RESOURCE_MANAGER,
    MATERIAL_MANAGER,
    EVENT_MANAGER,
    FURNITURE_MANAGER,
    AVATAR_MANAGER,
    RENDERER_FINISHED,
    NETWORK_ESTABLISHED,
    LOADED
}